### PR TITLE
[S] Code coverage with codecov

### PR DESCRIPTION
**Pull request by Istar-Eldritch**
Add code coverage with [Codecov](https://codecov.io/)

### CODE REVIEW

**Comment by Istar-Eldritch** [comment]
@tombyers @SebastianPlace take a look at the tests that are failing. Feel free to push patches to this se PR.

**Comment by SebastianPlace** [comment]
I'll take a look later today

**Review by SebastianPlace — COMMENTED** [review]
@Istar-Eldritch Is there a way we can check the coverage locally, before pushing. Presumably we need access to the codecov token?

Also it seems the coverage isn't being reported:
screen shot 2017-06-19 at 15 37 28

**Comment by Istar-Eldritch** [comment]
Ill add another commit tonight to add a command for it tonight

**Comment by Istar-Eldritch** [comment]
Ill also document it in the readme

**Comment by Istar-Eldritch** [comment]
@SebastianPlace I think this is ready to go. Check if you need to add anything else to the README.

**Review by SebastianPlace — APPROVED** [review]

**Comment by SebastianPlace** [comment]
Thanks for this @Istar-Eldritch 👍

**Pull request merged**
